### ISSUE TITLE
Is this an Implementation of [3] D. Shen, Y. Zhang, R. Henao, Q. Su, L. Carin, Deconvolutional Latent-Variable Model for Text Sequence Matching

### ISSUE THREAD

**Issue by nikhilrayaprolu** [btaille/semantic-question-matching#1]
Hello @btaille , So according to the description is this an implementation of [3] D. Shen, Y. Zhang, R. Henao, Q. Su, L. Carin, Deconvolutional Latent-Variable Model for Text Sequence Matching ?

**Comment by btaille** [comment]
Hello @nikhilrayaprolu, I agree the formulation is not clear but this is not an implementation of the DeconvLVM. I cited this paper because it reports results in a semi-supervised setting on Quora. The supervised model is an implementation of [1] A. Conneau, D. Kiela, H. Schwenk, L. Barrault, A. Bordes, Supervised Learning of Universal Sentence Representations from Natural Language Inference Data. And I added unsupervised pretraining of the encoder using a SDAE which (to my knowledge) has not been explored for semantic question matching, although [3] presents a similar idea.
